spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write_dates_as_timestamps: false
  jpa:
    properties:
      hibernate:
        format_sql: true
      jdbc:
        batch_size: 100
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  aop:
    proxy-target-class: false

feign:
  okhttp:
    enabled: true

logging:
  level:
    com:
      huangydyn: DEBUG
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: info
    root: WARN

test:
  value: origin
#If Using Baseline
#flyway.baselineOnMigrate=true
#flyway.baseline-version=1

