CREATE TABLE `hero` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  address VARCHAR(50) DEFAULT NULL,
  `created_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;